[package]
name = "boxdraw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
font-kit = "0.11.0"
minifb = "0.24.0"
nalgebra = "0.32.2"
raqote = "0.8.2"
